# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AvivDatabasePopulator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AvivDatabasePopulator
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'PromiseKit'

  target 'AvivDatabasePopulatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
