# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AVIV' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AVIV
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'PromiseKit', '~> 6.8'

  target 'AVIVTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
