# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AVIV' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

  # Pods for AVIV
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  pod 'Bolts'

  target 'AVIVTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
